# Generated by Django 5.2.4 on 2025-07-09 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_video_likes_video_watch_later"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="video",
            name="watch_later",
            field=models.ManyToManyField(
                blank=True, related_name="saved_videos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
